{
    'name': 'Tarombo',
    'version': '19.0.1.0.0',
    'summary': 'Pendataan dan pelestarian silsilah marga',
    'description': """
Platform pendataan, penelusuran, dan pelestarian silsilah marga (tarombo),
mengikuti kaidah pencatatan tarombo asli, bukan aplikasi silsilah umum.
""",
    'category': 'Tarombo',
    'author': 'Cv Sel Studio',
    'website': 'https://selstudio.id',
    'depends': ['base', 'mail', 'web'],
    'data': [
        'security/tarombo_security.xml',
        'security/ir.model.access.csv',
        'security/tarombo_usulan_security.xml',
        'security/tarombo_klaim_akun_security.xml',
        'views/tarombo_pohon_views.xml',
        'views/tarombo_dashboard_views.xml',
        'views/tarombo_orang_views.xml',
        'views/tarombo_marga_views.xml',
        'views/tarombo_padan_views.xml',
        'views/tarombo_wilayah_views.xml',
        'views/tarombo_punguan_views.xml',
        'views/tarombo_direktori_keahlian_views.xml',
        'views/tarombo_usulan_views.xml',
        'views/tarombo_klaim_akun_views.xml',
        'views/tarombo_arsip_views.xml',
        'wizard/tarombo_partuturan_wizard_views.xml',
        'views/menu.xml',
        'data/tarombo_marga_data.xml',
        'data/tarombo_wilayah_data.xml',
        'data/tarombo_punguan_data.xml',
        'data/tarombo_usulan_data.xml',
        'data/tarombo_klaim_akun_data.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'tarombo/static/lib/echarts/echarts.min.js',
            'tarombo/static/src/components/pohon/pohon.js',
            'tarombo/static/src/components/pohon/pohon.xml',
            'tarombo/static/src/components/pohon/pohon.scss',
            'tarombo/static/lib/leaflet/leaflet.css',
            'tarombo/static/lib/leaflet/leaflet.js',
            'tarombo/static/src/components/geo_picker/geo_picker.js',
            'tarombo/static/src/components/geo_picker/geo_picker.xml',
            'tarombo/static/src/components/geo_picker/geo_picker.scss',
            'tarombo/static/src/components/dashboard/dashboard.js',
            'tarombo/static/src/components/dashboard/dashboard.xml',
            'tarombo/static/src/components/dashboard/dashboard.scss',
        ],
    },
    'installable': True,
    'application': True,
    'sequence': 5,
    'license': 'LGPL-3',
    'post_init_hook': 'post_init_hook',
}
