from . import tarombo_orang
from . import tarombo_marga
from . import tarombo_padan
from . import tarombo_wilayah
from . import tarombo_punguan
from . import tarombo_pernikahan
from . import tarombo_partuturan
from . import tarombo_riwayat
from . import tarombo_usulan
from . import tarombo_arsip
from . import tarombo_pohon
from . import tarombo_dashboard
from . import tarombo_klaim_akun
from . import tarombo_lokasi_mobile
